//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Data.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.Data.Entity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上下文类型“{0}”不是IUnitOfWork接口的派生类.
        /// </summary>
        internal static string ContextTypeNotIUnitOfWorkType {
            get {
                return ResourceManager.GetString("ContextTypeNotIUnitOfWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是有效的上下文初始化类型.
        /// </summary>
        internal static string DatabaseInitializer_TypeNotDatabaseInitializer {
            get {
                return ResourceManager.GetString("DatabaseInitializer_TypeNotDatabaseInitializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称为“{0}”的数据库连接串不存在.
        /// </summary>
        internal static string DbContextBase_ConnectionStringNameNotExist {
            get {
                return ResourceManager.GetString("DbContextBase_ConnectionStringNameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上下文“{0}”初始化失败，实体映射程序集不存在.
        /// </summary>
        internal static string DbContextInitializerBase_MapperAssembliesIsEmpty {
            get {
                return ResourceManager.GetString("DbContextInitializerBase_MapperAssembliesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体类型“{0}”未映射到上下文中，请为实体派生 EntityConfigurationBase&lt;&gt; 类型，使之能被数据上下文加载。.
        /// </summary>
        internal static string DbContextManager_EntityTypeNotMaptoDbContext {
            get {
                return ResourceManager.GetString("DbContextManager_EntityTypeNotMaptoDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是 DbContextBase&lt;&gt; 类型的派生类.
        /// </summary>
        internal static string DbContextManager_TypeNotDbContextType {
            get {
                return ResourceManager.GetString("DbContextManager_TypeNotDbContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是实体类型.
        /// </summary>
        internal static string DbContextManager_TypeNotEntityType {
            get {
                return ResourceManager.GetString("DbContextManager_TypeNotEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体类“{0}”所属的上下文“{1}”获取失败.
        /// </summary>
        internal static string DbContextTypeResolver_DbContextResolveFailed {
            get {
                return ResourceManager.GetString("DbContextTypeResolver_DbContextResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓储中的 {0} 方法不支持事务操作.
        /// </summary>
        internal static string Repository_MethodNotSupportedTransaction {
            get {
                return ResourceManager.GetString("Repository_MethodNotSupportedTransaction", resourceCulture);
            }
        }
    }
}
