//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Web.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.Web.Mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是MVC控制器类型.
        /// </summary>
        internal static string ActionMethodInfoFinder_TypeNotMvcControllerType {
            get {
                return ResourceManager.GetString("ActionMethodInfoFinder_TypeNotMvcControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 声明功能“{0}”的类型为空.
        /// </summary>
        internal static string FunctionHandler_DefindActionTypeIsNull {
            get {
                return ResourceManager.GetString("FunctionHandler_DefindActionTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法“{0}”不是MVC的Action功能.
        /// </summary>
        internal static string FunctionHandler_MethodNotMvcAction {
            get {
                return ResourceManager.GetString("FunctionHandler_MethodNotMvcAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定功能只支持使用Ajax的方式来调用。.
        /// </summary>
        internal static string Mvc_ActionAttribute_AjaxOnlyMessage {
            get {
                return ResourceManager.GetString("Mvc_ActionAttribute_AjaxOnlyMessage", resourceCulture);
            }
        }
    }
}
